### PR TITLE
Fixed build codec issue

### PR DESCRIPTION
**Pull request by PK-Person**
Fixed downloading of codecs for different platforms

### CODE REVIEW

**Comment by ziro-official** [comment]
@PK-Person Thank for your PR, I'll review and merge by this weekend.

**Comment by PK-Person** [comment]
I think you are using Node to build code (The way used in Jenkin's file).
Could you use yarn? I want to remove one of the lock files as they are conflicting (yarn.lock or package-lock.json)
```
yarn install
yarn dist --platforms=win32
yarn dist --platforms=win64
yarn dist --platforms=linux32
yarn dist --platforms=linux64
yarn dist --platforms=osx64

```

**Comment by ziro-official** [comment]
I'm using npm to build the code. Didn't try yarn yet.

**Comment by PK-Person** [comment]
I think **npm** is very slow. GIve **yarn** a try, but delete package-lock.json before trying. Let me know which one you want to use and I will start using that one.

**Pull request merged**
